// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKHJuuVpm2nyTKVq4p4FtIGc-jt1DUkxw',
    appId: '1:240282301798:web:4d1e27b6ff236fa94ac4a7',
    messagingSenderId: '240282301798',
    projectId: 'moneymetang-1b9cd',
    authDomain: 'moneymetang-1b9cd.firebaseapp.com',
    storageBucket: 'moneymetang-1b9cd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVDfQVQo1QsazA94FqkT6-3_xBRg4pZRs',
    appId: '1:240282301798:android:fd304c784e8352de4ac4a7',
    messagingSenderId: '240282301798',
    projectId: 'moneymetang-1b9cd',
    storageBucket: 'moneymetang-1b9cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAVJtWhAcWi0p-N2H-9_SZj7q5hPdq-k4',
    appId: '1:240282301798:ios:4140a0388e3d05404ac4a7',
    messagingSenderId: '240282301798',
    projectId: 'moneymetang-1b9cd',
    storageBucket: 'moneymetang-1b9cd.appspot.com',
    iosBundleId: 'com.kantinunaundeesapplication.app.testProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAVJtWhAcWi0p-N2H-9_SZj7q5hPdq-k4',
    appId: '1:240282301798:ios:eb6cd189bbc0dade4ac4a7',
    messagingSenderId: '240282301798',
    projectId: 'moneymetang-1b9cd',
    storageBucket: 'moneymetang-1b9cd.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKHJuuVpm2nyTKVq4p4FtIGc-jt1DUkxw',
    appId: '1:240282301798:web:191d45f5634804734ac4a7',
    messagingSenderId: '240282301798',
    projectId: 'moneymetang-1b9cd',
    authDomain: 'moneymetang-1b9cd.firebaseapp.com',
    storageBucket: 'moneymetang-1b9cd.appspot.com',
  );
}
